censusmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(r'', include('core.urls')),
    # path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings


from . import views

app_name = 'core'

urlpatterns = [
    path(r'', views.PersonListView.as_view(), name='home'),
    path(r'department/', views.DepartmentListView.as_view(), name='department_list'),
    path(r'department/create', views.DepartmentCreateView.as_view(),
         name='department_create'),
    path(r'department/update/<int:pk>/', views.DepartmentUpdateView.as_view(),
         name='department_update'),
    path(r'department/delete/<int:pk>/', views.DepartmentDeleteView.as_view(),
         name='department_delete'),
    path(r'staff/', views.StaffListView.as_view(), name='staff_list'),
    path(r'staff/create', views.StaffCreateView.as_view(),
         name='staff_create'),
    path(r'staff/update/<int:pk>/', views.StaffUpdateView.as_view(),
         name='staff_update'),
    path(r'staff/delete/<int:pk>/', views.StaffDeleteView.as_view(),
         name='staff_delete'),
    path(r'state/', views.StateListView.as_view(), name='state_list'),
    path(r'state/create', views.StateCreateView.as_view(),
         name='state_create'),
    path(r'state/update/<int:pk>/', views.StateUpdateView.as_view(),
         name='state_update'),
    path(r'state/delete/<int:pk>/', views.StateDeleteView.as_view(),
         name='state_delete'),

    path(r'lga/', views.LGAListView.as_view(), name='lga_list'),
    path(r'lga/create', views.LGACreateView.as_view(),
         name='lga_create'),
    path(r'lga/update/<int:pk>/', views.LGAUpdateView.as_view(),
         name='lga_update'),
    path(r'lga/delete/<int:pk>/', views.LGADeleteView.as_view(),
         name='lga_delete'),
    path(r'accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path(r'accounts/logout/', auth_views.LogoutView.as_view(),
         {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path(r'person/', views.PersonListView.as_view(), name='person_list'),
    path(r'person/create', views.PersonCreateView.as_view(),
         name='person_create'),
    path(r'person/update/<int:pk>/', views.PersonUpdateView.as_view(),
         name='person_update'),
    path(r'person/delete/<int:pk>/', views.PersonDeleteView.as_view(),
         name='person_delete'),
    path(r'person/detail/<int:pk>/', views.PersonDetailView.as_view(),
         name='person_detail'),
]

core/models.py
from django.db import models


class Department(models.Model):
    department_name = models.CharField(max_length=250)
    department_head = models.CharField(max_length=250)
    number_of_staffs = models.IntegerField()
    date_of_creation = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.department_name


class Staff (models.Model):
    SEX = (
        ["Male", "Male"],
        ["Female", "Female"]
    )
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    other_name = models.CharField(max_length=255)
    sex = models.CharField(max_length=25, choices=SEX)
    DOB = models.DateField()
    address = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=15)
    email = models.EmailField()
    department = models.ForeignKey(
        Department, on_delete=models.CASCADE, related_name="staffs")
    start_date = models.DateField()
    end_date = models.DateField()
    higher_qualification = models.CharField(max_length=25)
    result_obtained = models.CharField(max_length=150)
    school_attended = models.CharField(max_length=250)
    date_obtained = models.DateField()
    other_qualification = models.CharField(max_length=255)
    professional_qualification = models.CharField(max_length=250)

    def fullname(self):
        return self.last_name+" "+self.first_name+" "+self.other_name

    def __str__(self):
        return self.last_name+" "+self.first_name+" "+self.other_name


class State(models.Model):
    state_name = models.CharField(max_length=250)
    state_zone = models.CharField(max_length=15)

    def __str__(self):
        return self.state_name


class LGA(models.Model):
    lga_name = models.CharField(max_length=250)
    lga_zone = models.CharField(max_length=15)
    lga_state = models.ForeignKey(
        State, on_delete=models.CASCADE, related_name="lgas")

    def __str__(self):
        return self.lga_name


class Person(models.Model):
    SEX = (
        ["Male", "Male"],
        ["Female", "Female"]
    )
    DISABLED = (
        ["Yes", "Yes"],
        ["No", "No"]
    )
    WORK_STATUS = (
        ["Employed", "Employed"],
        ["Unemployed", "Unemployed"]
    )
    surname = models.CharField(max_length=250)
    first_name = models.CharField(max_length=250)
    other_name = models.CharField(max_length=250)
    current_age = models.IntegerField()
    DOB = models.DateField()
    sex = models.CharField(max_length=25, choices=SEX)
    nationality = models.CharField(max_length=150)
    residential_state = models.ForeignKey(
        State, on_delete=models.CASCADE, related_name='state_residents')
    residential_lga = models.ForeignKey(
        LGA, on_delete=models.CASCADE, related_name='lga_residents')
    residential_town = models.CharField(max_length=150)
    occupation = models.CharField(max_length=150)
    state_of_birth = models.ForeignKey(
        State, on_delete=models.CASCADE, related_name='state_of_birth')
    lga_of_birth = models.ForeignKey(
        LGA, on_delete=models.CASCADE, related_name='lga_of_birth')
    disabled = models.CharField(max_length=25, choices=DISABLED)
    work_status = models.CharField(max_length=25, choices=WORK_STATUS)

    def __str__(self):
        return self.surname+" "+self.first_name+" "+self.other_name

    def fullname(self):
        return self.surname+" "+self.first_name+" "+self.other_name

core/forms.py
from django import forms

from .models import Department, Staff, Person, State, LGA


class DepartmentCreateForm(forms.ModelForm):

    class Meta:
        model = Department
        fields = ('department_name', 'department_head', 'number_of_staffs')


class StaffCreateForm(forms.ModelForm):
    DOB = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'type': 'date'}))
    end_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))
    date_obtained = forms.DateField(
        widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Staff
        fields = ('first_name', 'last_name', 'other_name', 'sex', 'DOB', 'address', 'phone_number',
                  'email', 'department', 'start_date', 'end_date', 'higher_qualification', 'result_obtained',
                  'school_attended', 'date_obtained', 'other_qualification',
                  'professional_qualification')


class PersonCreateForm(forms.ModelForm):
    DOB = forms.DateField(widget=forms.TextInput(attrs={"type": "date"}))

    class Meta:
        model = Person
        fields = ('surname', 'first_name', 'other_name', 'current_age', 'DOB', 'sex', 'nationality',
                  'residential_state', 'residential_lga', 'residential_town', 'occupation', 'state_of_birth', 'lga_of_birth', 'disabled', 'work_status',)


class StateCreateForm(forms.ModelForm):

    class Meta:
        model = State
        fields = ('state_name', 'state_zone')


class LGACreateForm(forms.ModelForm):

    class Meta:
        model = LGA
        fields = ('lga_name', 'lga_zone', 'lga_state')

core/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, CreateView, UpdateView, DetailView, DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import (StateCreateForm, DepartmentCreateForm,
                    StaffCreateForm, StateCreateForm, LGACreateForm, PersonCreateForm)
from .models import (Person, Department, Staff, State, LGA,)


class HomeView(LoginRequiredMixin, ListView):
    model = Person
    template_name = 'dashboard/index.html'


class DepartmentListView(LoginRequiredMixin, ListView):
    model = Department
    template_name = 'dashboard/department/list.html'


class DepartmentCreateView(LoginRequiredMixin, CreateView):
    form_class = DepartmentCreateForm
    template_name = 'dashboard/department/create.html'
    success_url = reverse_lazy('core:department_list')


class DepartmentUpdateView(LoginRequiredMixin, UpdateView):
    model = Department
    form_class = DepartmentCreateForm
    template_name = 'dashboard/department/update.html'
    success_url = reverse_lazy('core:department_list')


class DepartmentDeleteView(LoginRequiredMixin, DeleteView):
    model = Department
    form_class = DepartmentCreateForm
    template_name = 'dashboard/department/delete.html'
    success_url = reverse_lazy('core:department_list')


class StaffListView(LoginRequiredMixin, ListView):
    model = Staff
    template_name = 'dashboard/staff/list.html'


class StaffCreateView(LoginRequiredMixin, CreateView):
    form_class = StaffCreateForm
    template_name = 'dashboard/staff/create.html'
    success_url = reverse_lazy('core:staff_list')


class StaffUpdateView(LoginRequiredMixin, UpdateView):
    model = Staff
    form_class = StaffCreateForm
    template_name = 'dashboard/staff/update.html'
    success_url = reverse_lazy('core:staff_list')


class StaffDeleteView(LoginRequiredMixin, DeleteView):
    model = Staff
    template_name = 'dashboard/staff/delete.html'
    success_url = reverse_lazy('core:staff_list')


class StateListView(LoginRequiredMixin, ListView):
    model = State
    template_name = 'dashboard/state/list.html'


class StateCreateView(LoginRequiredMixin, CreateView):
    form_class = StateCreateForm
    template_name = 'dashboard/state/create.html'
    success_url = reverse_lazy('core:state_list')


class StateUpdateView(LoginRequiredMixin, UpdateView):
    model = State
    form_class = StateCreateForm
    template_name = 'dashboard/state/update.html'
    success_url = reverse_lazy('core:state_list')


class StateDeleteView(LoginRequiredMixin, DeleteView):
    model = State
    template_name = 'dashboard/state/delete.html'
    success_url = reverse_lazy('core:state_list')


class LGAListView(LoginRequiredMixin, ListView):
    model = LGA
    template_name = 'dashboard/lga/list.html'


class LGACreateView(LoginRequiredMixin, CreateView):
    form_class = LGACreateForm
    template_name = 'dashboard/lga/create.html'
    success_url = reverse_lazy('core:lga_list')


class LGAUpdateView(LoginRequiredMixin, UpdateView):
    model = LGA
    form_class = LGACreateForm
    template_name = 'dashboard/lga/update.html'
    success_url = reverse_lazy('core:lga_list')


class LGADeleteView(LoginRequiredMixin, DeleteView):
    model = LGA
    template_name = 'dashboard/lga/delete.html'
    success_url = reverse_lazy('core:lga_list')


class PersonListView(LoginRequiredMixin, ListView):
    model = Person
    template_name = 'dashboard/person/list.html'


class PersonCreateView(LoginRequiredMixin, CreateView):
    form_class = PersonCreateForm
    template_name = 'dashboard/person/create.html'
    success_url = reverse_lazy('core:person_list')


class PersonUpdateView(LoginRequiredMixin, UpdateView):
    model = Person
    form_class = PersonCreateForm
    template_name = 'dashboard/person/update.html'
    success_url = reverse_lazy('core:person_list')


class PersonDeleteView(LoginRequiredMixin, DeleteView):
    model = Person
    template_name = 'dashboard/person/delete.html'
    success_url = reverse_lazy('core:person_list')


class PersonDetailView(LoginRequiredMixin, DetailView):
    model = Person
    template_name = 'dashboard/person/detail.html'

core/templates/dashboard/staff/create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block page_head %}
<h3><i class="fa fa-angle-right"></i> Manage Staffs</h3>
{% endblock page_head %}


{% block content %}
<div class="col-lg-offset-1 col-lg-8">
    <div class="form-panel">
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-theme" type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock content %}

core/templates/dashboard/staff/delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block page_head %}
<h3><i class="fa fa-angle-right"></i> Manage Staffs</h3>
{% endblock page_head %}


{% block content %}
<div class="col-lg-offset-1 col-lg-8">
    <div class="alert alert-danger">
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" class="btn btn-danger" value="Confirm">
        </form>
    </div>
</div>
{% endblock content %}

core/templates/dashboard/staff/list.html
{% extends 'base.html' %}
{% load static %}


{% block page_head %}
<h3><i class="fa fa-angle-right"></i> Manage Staffs</h3>
<a href="{% url 'core:staff_create' %}" class="btn btn-theme pull-right" type="submit"><i class="fa fa-plus"></i> Add
    Staff</a>
{% endblock page_head %}


{% block content %}
<div class="col-lg-12">
    <div class="row">

        {% for staff in staff_list %}
        <div class="col-lg-4 col-md-4 col-sm-4 mb">
            <div class="content-panel pn" style="background: #444c57;">
                <div id="profile-01" style="background: #444c57;">
                    <h3>{{staff.fullname}}</h3>
                    <h6>{{staff.department}} Department</h6>
                </div>
                <div class="col-lg-offset-1 col-lg-10 centered mt">
                    <a href="{% url 'core:staff_update' staff.id %}" class="btn btn-sm btn-theme" type="submit"><i
                            class="fa fa-pencil"></i> Edit</a>
                    <a href="{% url 'core:staff_delete' staff.id %}" class="btn btn-sm btn-theme04" type="button"><i
                            class="fa fa-trash"></i> Delete</a>
                </div>
                <div class="centered">
                    <h6>{{staff.email}}</h6>
                </div>
            </div>
            <!-- /content-panel -->
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

core/templates/dashboard/staff/update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block page_head %}
<h3><i class="fa fa-angle-right"></i> Manage Staffs</h3>
{% endblock page_head %}


{% block content %}
<div class="col-lg-offset-1 col-lg-8">
    <div class="form-panel">
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-theme" type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock content %}